// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_app/config/environment_config.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: EnvironmentConfig.firebaseWebApiKey,
    appId: '1:981202726546:web:be4645d53dc53fc0b7404b',
    messagingSenderId: '981202726546',
    projectId: 'fir-example-ebbe9',
    authDomain: 'fir-example-ebbe9.firebaseapp.com',
    storageBucket: 'fir-example-ebbe9.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: EnvironmentConfig.firebaseAndroidApiKey,
    appId: '1:981202726546:android:708fe3b57aaf27f3b7404b',
    messagingSenderId: '981202726546',
    projectId: 'fir-example-ebbe9',
    storageBucket: 'fir-example-ebbe9.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: EnvironmentConfig.firebaseIosApiKey,
    appId: '1:981202726546:ios:d38bfc08119bf302b7404b',
    messagingSenderId: '981202726546',
    projectId: 'fir-example-ebbe9',
    storageBucket: 'fir-example-ebbe9.appspot.com',
    iosClientId:
        '981202726546-rbqev487rp5o04l8inlah33uu6oghbke.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: EnvironmentConfig.firebaseMacOsApiKey,
    appId: '1:981202726546:ios:d38bfc08119bf302b7404b',
    messagingSenderId: '981202726546',
    projectId: 'fir-example-ebbe9',
    storageBucket: 'fir-example-ebbe9.appspot.com',
    iosClientId:
        '981202726546-rbqev487rp5o04l8inlah33uu6oghbke.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
